// Generated by CoffeeScript 1.10.0
(function() {
  "use strict";
  var FONT, Phaser, RATE, SECOND, SIZE, TEXT;

  Phaser = this.Phaser;

  FONT = "fonts/bitmapFonts/nokia16";

  RATE = 20;

  SECOND = 1000;

  SIZE = 16;

  TEXT = "THE EVE OF THE WAR \n\nNo one would have believed in the last years of the nineteenth century that this world was being watched keenly and closely by intelligences greater than man's and yet as mortal as his own; that as men busied themselves about their various concerns they were scrutinised and studied, perhaps almost as narrowly as a man with a microscope might scrutinise the transient creatures that swarm and multiply in a drop of water. With infinite complacency men went to and fro over this globe about their little affairs, serene in their assurance of their empire over matter. It is possible that the infusoria under the microscope do the same. No one gave a thought to the older worlds of space as sources of human danger, or thought of them only to dismiss the idea of life upon them as impossible or improbable. It is curious to recall some of the mental habits of those departed days. At most terrestrial men fancied there might be other men upon Mars, perhaps inferior to themselves and ready to welcome a missionary enterprise. Yet across the gulf of space, minds that are to our minds as ours are to those of the beasts that perish, intellects vast and cool and unsympathetic, regarded this earth with envious eyes, and slowly and surely drew their plans against us.";

  window.GAME = new Phaser.Game({
    antialias: false,
    scaleMode: Phaser.ScaleManager.NO_SCALE,
    state: {
      init: function() {
        this.game.plugins.add(Phaser.Plugin.DebugTween);
      },
      preload: function() {
        this.load.baseURL = "http://examples.phaser.io/assets/";
        this.load.crossOrigin = "anonymous";
        this.load.bitmapFont("font", FONT + ".png", FONT + ".xml");
        this.load.image("atari", "sprites/atari130xe.png");
        this.load.image("starfield", "skies/starfield.png");
      },
      create: function() {
        var atari, stars;
        stars = this.add.tileSprite(0, 0, 800, 600, "starfield");
        atari = this.add.image(0, 0, "atari").alignIn(this.world.bounds, Phaser.CENTER, 0, 200);
        this.text = this.add.bitmapText(100, 50, "font", null, SIZE);
        this.text.blendMode = Phaser.blendModes.ADD;
        this.text.maxWidth = 600;
        this.text.tint = 0x0099ff;
        this.options = {
          autoStart: true,
          rate: RATE,
          cursorChar: "_",
          text: TEXT,
          textTarget: this.text
        };
        this.type = this.add.teletype(this.options);
        this.type.onComplete.add(this.onTypeComplete, this);
        this.add.tween(stars.tilePosition).to({
          x: this.world.width,
          y: this.world.height
        }, this.type.totalDuration).start();
        this.add.tween(atari).from({
          alpha: 0,
          y: this.world.height
        }, SECOND, "Quad").start();
        this.textTween = this.add.tween(this.text).from({
          alpha: 0,
          y: 0
        }, SECOND, "Quad").start();
      },
      render: function() {},
      onTypeComplete: function() {
        this.add.tween(this.text).to({
          alpha: 0,
          y: 0
        }, 2 * SECOND, "Quad").delay(2 * SECOND).start();
      }
    }
  });

}).call(this);
