// Generated by CoffeeScript 1.10.0
(function() {
  "use strict";
  var Phaser, Teletype,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Phaser = this.Phaser;

  Phaser.Tween.Teletype = Teletype = (function(superClass) {
    extend(Teletype, superClass);

    Teletype.prototype.rate = null;

    Teletype.prototype.cursorChar = "";

    function Teletype(target, game, manager, options) {
      this.text = options.text;
      target = {
        length: this.text.length
      };
      Teletype.__super__.constructor.call(this, target, game, manager);
      this.cursorChar = options.cursorChar;
      this.textTarget = options.textTarget;
      if (options.rate) {
        options.duration = 1000 * this.text.length / options.rate;
      }
      this.from({
        length: 0
      }, options.duration, "Linear", options.autoStart, options.delay).onUpdateCallback(this.onUpdate, this);
    }

    Teletype.prototype.onUpdate = function(tween, val) {
      this.textTarget.text = this.text.slice(0, ~~(0.5 + val * this.text.length)) + this.cursorChar;
    };

    return Teletype;

  })(Phaser.Tween);

  Phaser.GameObjectFactory.prototype.teletype = function(options) {
    return new Phaser.Tween.Teletype(null, this.game, this.game.tweens, options);
  };

}).call(this);
